name: Build Fineract WAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build WAR file
        run: ./gradlew clean build -x test

      - name: Upload WAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fineract-provider
          path: build/libs/fineract-provider.war
